export * from './asignaturas';
export * from './asistencia';
export * from './auth';
export * from './gradoGrupo';
export * from './grados';
export * from './grupos';
export * from './home';
export * from './ingresos';
export * from './notas';